# Generated by Django 4.2.14 on 2025-10-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.CharField(max_length=50, unique=True)),
                ('dept_id', models.IntegerField()),
                ('initial_cost', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('buy_qty_suggested_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StoresMaster',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetOTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_month', models.CharField(max_length=10)),
                ('dept_id', models.IntegerField()),
                ('allocated_receipts', models.FloatField()),
            ],
            options={
                'unique_together': {('dept_id', 'fiscal_year', 'fiscal_month')},
            },
        ),
        migrations.CreateModel(
            name='TransactionsSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('sale_quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storesmaster')),
            ],
            options={
                'indexes': [models.Index(fields=['sale_date', 'store'], name='api_transac_sale_da_07af87_idx')],
            },
        ),
    ]
