# Generated by Django 4.2.14 on 2025-10-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetOTB',
            fields=[
                ('pk_otb', models.CharField(db_column='pk_otb', max_length=20, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_month', models.CharField(max_length=3)),
                ('dept_id', models.IntegerField()),
                ('allocated_receipts', models.DecimalField(decimal_places=2, max_digits=12)),
                ('based_on_cogs_ly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('otb_status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Budget OTB',
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('pk_sku', models.CharField(db_column='pk_sku', max_length=50, primary_key=True, serialize=False)),
                ('style_id', models.CharField(max_length=20)),
                ('vendor_id', models.CharField(max_length=50)),
                ('dept_id', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('color_id', models.CharField(max_length=10)),
                ('size_us', models.DecimalField(decimal_places=1, max_digits=4)),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('core_rep_flag', models.CharField(max_length=10)),
                ('repeat_new_flag', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Products Master',
            },
        ),
        migrations.CreateModel(
            name='StoresMaster',
            fields=[
                ('store_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('store_location', models.CharField(max_length=100)),
                ('store_cluster', models.CharField(max_length=10)),
                ('store_type', models.CharField(max_length=10)),
                ('max_option_capacity', models.IntegerField()),
                ('opening_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Stores Master',
            },
        ),
        migrations.CreateModel(
            name='TransactionsSales',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('quantity_sold', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gm_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku_id', models.ForeignKey(db_column='sku_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.productmaster')),
                ('store_id', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.storesmaster')),
            ],
            options={
                'verbose_name_plural': 'Transactions Sales',
            },
        ),
    ]
