# Generated by Django 4.2.14 on 2025-10-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesmaster',
            name='store_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
